name: xbatcher
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.8
  - dask
  - docrep
  - ipython
  - matplotlib
  - nbsphinx
  - numpy
  - numpydoc
  - pytest
  - sphinx
  - sphinx-autosummary-accessors
  - sphinx-copybutton
  - sphinx_rtd_theme
  - xarray
  - pip
